// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6224.frc2017.subsystems;

import org.usfirst.frc6224.frc2017.RobotMap;
import org.usfirst.frc6224.frc2017.commands.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Cycler extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final  subsystems = RobotMap.subsystems;
    private final JoystickButton yMovementButton = RobotMap.yMovementButton;
    private final JoystickButton turning = RobotMap.turning;
    private final JoystickButton intakeButton = RobotMap.intakeButton;
    private final JoystickButton throttleSwitch = RobotMap.throttleSwitch;
    private final Joystick drivingJoystick = RobotMap.drivingJoystick;
    private final JoystickButton cyclerButton = RobotMap.cyclerButton;
    private final JoystickButton shooterButton = RobotMap.shooterButton;
    private final Joystick shootingandCyclingJoystick = RobotMap.shootingandCyclingJoystick;
    private final  operatorInterface = RobotMap.operatorInterface;
    private final  yMovement = RobotMap.yMovement;
    private final  intake = RobotMap.intake;
    private final  shooter = RobotMap.shooter;
    private final  xMovement = RobotMap.xMovement;
    private final  throttle = RobotMap.throttle;
    private final  commands = RobotMap.commands;
    private final  frc2017 = RobotMap.frc2017;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ${name.replace(' ', '')}());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

